title: Homotopy Groups of Spheres
description: A table of the homotopy groups of sphere, proof coming soon!

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:categories/:year/:month/:day/:title/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate]
plugins: [jekyll-paginate]
